export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';

//Wizard Steps
export const WIZARD_STEP_NEXT = 'WIZARD_STEP_NEXT';
export const WIZARD_STEP_PREVIOUS = 'WIZARD_STEP_PREVIOUS';