export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_QUOTE_FORM_FIELD = 'UPDATE_QUOTE_FORM_FIELD';
export const UPDATE_NUMBERS = 'UPDATE_NUMBERS';
export const RESET_FORM = 'RESET_FORM';

//Calculate Quote
export const CALCULATE_QUOTE_REQUEST = 'CALCULATE_QUOTE_REQUEST';
export const CALCULATE_QUOTE_SUCCESS = 'CALCULATE_QUOTE_SUCCESS';
export const CALCULATE_QUOTE_FAILURE = 'CALCULATE_QUOTE_FAILURE';
