export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS';
export const GET_VENUES_FAILURE = 'GET_VENUES_FAILURE';
export const GET_VENUES_LOADING = 'GET_VENUES_LOADING';
export const SELECT_VENUE_SUCCESS = 'SELECT_VENUE_SUCCESS';
export const RESET_VENUES = 'RESET_VENUES';
